version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
  back-tunely:
    image: happy98/back-tunely:v0
    container_name: back-tunely
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    restart: unless-stopped
volumes:
  mongodb-data:

